### PR TITLE
Cmake

### PR DESCRIPTION
**Pull request by andriish**
Here is the basic version.
More functions and classes should be interfaced.

### CODE REVIEW

**Comment by HDembinski** [comment]
I gladly include the new writers from this patch.

I don't see the benefit of having a cmake build since we cannot get rid of the setup.py build, since it is needed to have the package pip-installable. If we cannot get rid of the setup.py, there is no benefit in adding another build system.

**Comment by HDembinski** [comment]
A proposed compromise: We want to have a cmake-based build that is steered from setup.py, so that the package can be build with cmake and by pip. I haven't tried this yet, but here is an example that looks like we could adapt it:
https://github.com/pybind/cmake_example

**Comment by HDembinski** [comment]
Also, please fork from the main repository https://github.com/scikit-hep/pyhepmc, this is my own private development fork.

**Comment by HDembinski** [comment]
I updated the master, now this patch has conflicts.

**Comment by HDembinski** [comment]
Adding pybind11 to the repository is not necessary, since this is installed automatically with pip.

**Comment by HDembinski** [comment]
It seems like this is the solution: https://scikit-build.readthedocs.io/en/latest/usage.html#basic-usage-example

**Comment by andriish** [comment]
Hi Hans,
1) concerning the cmake -- yes, you are right, there are many nice examples of usage of cmake for python modules. Another example I saw is 100% ready to be copied https://www.benjack.io/2017/06/12/python-cpp-tests.html   In that example, I assume, cmake builds can be used in parallel to the python setuptools.
Essentially all these cmake builds are trivial -- it is just add_module( ) + setting flags. Like the CMakeLists.txt I've created.
2) Concerning the separate pybind11 package -- it makes very little sense, as for me. The whole idea of header-only library is to be embedded in other codes.   In addition to that -- please remember that everything should work in standard production systems with system-wide installation of all packages.
That means  if the pybind11 is left as an external dependency, we are entering the dependency hell.
Very few systems have packages for pybind11. And if the packages are there, these should match the specific python version and specific basic requirements (e.g. RPM).
For instance the pybind is available on the following platforms  https://repology.org/project/python:pybind11/versions . No CentOS7.  And to install on CentOS7 one would need to recompile the src.rpm which again is tricky(yes!), install that manually and so on. There are no benefits in making the pybind11 external dependency in comparison to embedding.

3) OK, I'll clone another repo.

Best regards,
Andrii

**Comment by HDembinski** [comment]
2. You are thinking in terms of distribution packages, but the Python ecosystem does not depend on distribution packages. Everything is installed by pip, it is the ultimate package manager in Python. pip can install pybind11, cmake, and ninja on a pristine system. Basically, pip can install everything that is needed to build this project on any new computer. There is no problem with a dependency hell. pip gets these packages from PyPI https://pypi.org/, the official Python package repository. It is possible to pin the version of each package, so that only this version is installed as a dependency. This means that the dependencies can be fixed to a specific version by us without adding the source code directly to our repository.

**Comment by andriish** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hi Hans,Yes, I know how pip works, but please remember that there are other systems and other ways to install software. And things should work there as well. That doesnt mean that one should reject pip, of course.Andrii                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: 12 August 2019 18:03To: pyhepmc@noreply.github.comReply to: reply@reply.github.comCc: andrii.verbytskyi@desy.de; author@noreply.github.comSubject: Re: [HDembinski/pyhepmc] Cmake (#1)  You are thinking in terms of distribution packages, but the Python ecosystem does not depend on distribution packages. Everything is installed by pip, it is the ultimate package manager in Python. pip can install pybind11, cmake, and ninja on a pristine system. Basically, pip can install everything that is needed to build this project on any new computer. There is no problem with a dependency hell. pip gets these packages from PyPI https://pypi.org/, the official Python package repository. It is possible to pin the version of each package, so that only this version is installed as a dependency. This means that the dependencies can be fixed to a specific version by us without adding the source code directly to our repository.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by HDembinski** [comment]
> Hi Hans,Yes, I know how pip works, but please remember that there are other systems and other ways to install software. And things should work there as well. That doesn't mean that one should reject pip, of course.

My point is that users of pyhepmc-ng will use pip to install it from PyPI. Therefore, there is no need to provide another way of installing it. I don't understand why you want to install pyhepmc-ng in any other way.

My argument was from the very beginning that we cannot get rid of setup.py, because that is needed to make the package pip-installable as it is right now. This is expected by Python users. The installation works absolutely fine as it is right now without CMake. Not needing cmake is an advantage, because you can then install pyhepmc-ng even on a pristine system that doesn't have cmake installed.

My understanding was that you want the CMake-based build because HepMC3 itself is using a CMake-based build. But for the Python user perspective, the CMake build adds nothing; on the contrary, it requires that CMake has to be present on the system where this package is installed.

I am trying to understand your goal, which is not clear to me. I think you want to be able to compile pyhepmc-ng as a Debian or RPM package. This you can do with setup.py, there is no need to add a CMake build.

Let me summarize what I think we agree on.

1. We want this package to be pip-installable from PyPI on a pristine system that only has a C++ compiler and the minimal Python environment. This forces us to use setup.py and the setuptools package, which is the standard build and distribution system in Python (whether I like or not).
2. We want to be able to make RPMs from this package, because the standard distributions at CERN are RPM-based. This should already work, because setuptools supports building rpms. You can do `python setup.py bdist_rpm`.

Do you have other requirements? Because if not then the best solution is to not have a CMake-build for pyhepmc-ng (less maintenance burden, since no build system is duplicated).

**Comment by andriish** [comment]
Dear Hans,
On Tue, 2019-08-13 at 02:02 -0700, Hans Dembinski wrote:
> > Hi Hans,Yes, I know how pip works, but please remember that there
> > are other systems and other ways to install software. And things
> > should work there as well. That doesn't mean that one should reject
> > pip, of course.
> 
> My point is that users of pyhepmc-ng will use pip to install it from
> PyPI. Therefore, there is no need to provide another way of
> installing it. I don't understand why you want to install pyhepmc-ng
> in any other way.
That is the point that there are use cases for installation without
pip, PyPi and any other python managers like conda.

> My argument was from the very beginning that we cannot get rid of
> setup.py, because that is needed to make the package pip-installable
> as it is right now. This is expected by Python users. The
> installation works absolutely fine as it is right now without CMake. 
That is absolutely OK.
> Not needing cmake is an advantage, because you can then install
> pyhepmc-ng even on a pristine system that doesn't have cmake
> installed.
cmake is an explicit build dependency for hepmc3. 
> My understanding was that you want the CMake-based build because
> HepMC3 itself is using a CMake-based build. But for the Python user
> perspective, the CMake build adds nothing; on the contrary, it
> requires that CMake has to be present on the system where this
> package is installed.
> 
> I am trying to understand your goal, which is not clear to me. I
> think you want to be able to compile pyhepmc-ng as a Debian or RPM
> package. 
To make hepmc3 fit to all repositories and make installation and
distribution as easy as possible. Without any need even for non-
standard installation in 99% of cases.
> This you can do with setup.py, there is no need to add a CMake build.
If to have hepmc3+python bindings in one package, cmake should be
present anyway. There is no reasonable scenario when it is not the
case, simply because cmake is a dependency of hepmc  and not vice
verse,  see attachment.

> Let me summarize what I think we agree on.
> 
> 
> We want this package to be pip-installable from PyPI on a pristine
> system that only has a C++ compiler and the minimal Python
> environment. This forces us to use setup.py and the setuptools
> package, which is the standard build and distribution system in
> Python (whether I like or not).
> We want to be able to make RPMs from this package, because the
> standard distributions at CERN are RPM-based. This should already
> work, because setuptools supports building rpms.
> You can do python setup.py bdist_rpm.
That is not how it works. There are well-defined rules how to build
packages out of sources for all major distributions --
fedora/centos/debian/ubuntu etc. This is a way for  rehdat/fedora -- 
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/Please
 note that pip is not used there even when the sources are taken from
PYPI.
And this is an actual real-world example -- pythia8 python bindings
https://src.fedoraproject.org/rpms/pythia8/blob/master/f/pythia8.specPlease
 note here the way compilation is done and the required
dependencies.Even python itself is *NOT* required. This approach also
makes the compilation easier -- one can build for multiple python
simultaneously w/o any hacks.
Best regards,Andrii

**Comment by HDembinski** [comment]
> cmake is an explicit build dependency for hepmc3.

That is true, but you can build pyhepmc right now without CMake, and I would prefer to keep it this way, because it makes the installation easier for people who use pip and PyPI, which is the vast majority of Python users. You need to trust me a bit on this. People who use Python regularly use pip and conda to install Python packages, they do not bother with apt, rpm, etc.

> To make hepmc3 fit to all repositories and make installation and
distribution as easy as possible. Without any need even for non-
standard installation in 99% of cases.

There are simply different requirements for Python packages and C++ packages. In the C++ world, CMake is the standard now. In the Python world, this is setuptools. This is the standard installation tool / build system in the Python world, not CMake.

I see now problem with having a CMake build when you want to build C++ HepMC3 and a Python build when you want to build pyhepmc. You agree that we cannot get rid of setup.py, so if we have to keep anyway, there is no advantage in delegating to CMake to actually build the project, but there are disadvantages for pure Python users which I pointed out.

> If to have hepmc3+python bindings in one package, cmake should be
present anyway. There is no reasonable scenario when it is not the
case, simply because cmake is a dependency of hepmc  and not vice
verse,  see attachment.

Yes, it will be present, but CMake doesn't have to be used by setup.py. I see it like this, when you build the C++ HepMC3 library, you usually don't want to build the Python bindings. When you want the Python bindings, you don't want the C++ HepMC3 library. The two systems can coexist. This is so, because Python users will not bother downloading the HepMC3 code and compile it. They want to just pip-install things and not be bothered by manually downloading source code and compiling it.

For me it is very important that `pip install pyhepmc-ng` works on a pristine system that doesn't even have CMake installed.

> That is not how it works. There are well-defined rules how to build
packages out of sources for all major distributions --
fedora/centos/debian/ubuntu etc. This is a way for  rehdat/fedora --
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/Please
 note that pip is not used there even when the sources are taken from
PYPI.

The links don't work for me, I cannot check.

> And this is an actual real-world example -- pythia8 python bindings
https://src.fedoraproject.org/rpms/pythia8/blob/master/f/pythia8.specPlease
 note here the way compilation is done and the required
dependencies.Even python itself is *NOT* required. This approach also
makes the compilation easier -- one can build for multiple python
simultaneously w/o any hacks.

setup.py is the standard way to build distribution packages according to the Python docs:
https://docs.python.org/3/distutils/builtdist.html

You cannot use pythia8 as a typical example, because it is not a typical Python package. Everything that I am telling you, however, is standard in the Python community. You argue like you know the Python ecosphere very well, but I think I know it better than you.

**Comment by HDembinski** [comment]
I will modify this PR to keep the new writers but undo the other changes. I added the pybind11 code as a git submodule now in the master, which is better than adding copies of the pybind11 files. It seems we cannot reach a consensus on what to with the cmake build and I therefore I propose to move this to another PR.

**Comment by andriish** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}                                                                                                                                                                                                                                                                                                                                                     From: notifications@github.comSent: 14 August 2019 12:11To: pyhepmc@noreply.github.comReply to: reply@reply.github.comCc: andrii.verbytskyi@desy.de; author@noreply.github.comSubject: Re: [HDembinski/pyhepmc] Cmake (#1)  
cmake is an explicit build dependency for hepmc3.

That is true, but you can build pyhepmc right now without CMake, and I would prefer to keep it this way,Perfectly fine! because it makes the installation easier for people who use pip and PyPI, which is the vast majority of Python users. You need to trust me a bit on this. People who use Python regularly use pip and conda to install Python packages, they do not bother with apt, rpm, etc.

To make hepmc3 fit to all repositories and make installation and
distribution as easy as possible. Without any need even for non-
standard installation in 99% of cases.

There are simply different requirements for Python packages and C++ packages. In the C++ world, CMake is the standard now.Sad but no. Autotools. In the Python world, this is setuptools. This is the standard installation tool / build system in the Python world, not CMake.Personally i do agree, but don't tell that to conda fans.
I see now problem with having a CMake build when you want to build C++ HepMC3 and a Python build when you want to build pyhepmc. You agree that we cannot get rid of setup.py, so if we have to keep anyway, there is no advantage in delegating to CMake to actually build the project, but there are disadvantages for pure Python users which I pointed out.Having one more file in the repo is very small price to pay for consistent compilation and linkage and least on some platforms. As for me that is not a big deal at all.

If to have hepmc3+python bindings in one package, cmake should be
present anyway. There is no reasonable scenario when it is not the
case, simply because cmake is a dependency of hepmc  and not vice
verse,  see attachment.

Yes, it will be present, but CMake doesn't have to be used by setup.py. I see it like this, when you build the C++ HepMC3 library, you usually don't want to build the Python bindings. When you want the Python bindings, you don't want the C++ HepMC3 library. Disagree. The best practice is to build everything in one step and install "as needed".The two systems can coexist. This is so, because Python users will not bother downloading the HepMC3 code and compile it. They want to just pip-install things and not be bothered by manually downloading source code and compiling it.
For me it is very important that pip install pyhepmc-ng works on a pristine system that doesn't even have CMake installed.

That is not how it works. There are well-defined rules how to build
packages out of sources for all major distributions --
fedora/centos/debian/ubuntu etc. This is a way for  rehdat/fedora --
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/Please
note that pip is not used there even when the sources are taken from
PYPI.Uh, the space was missinghttps://docs.fedoraproject.org/en-US/packaging-guidelines/Python/

The links don't work for me, I cannot check.

And this is an actual real-world example -- pythia8 python bindings
https://src.fedoraproject.org/rpms/pythia8/blob/master/f/pythia8.specPlease
note here the way compilation is done and the required
dependencies.Even python itself isNOT required. This approach also
makes the compilation easier -- one can build for multiple python
simultaneously w/o any hacks.

setup.py is the standard way to build distribution packages according to the Python docs:
https://docs.python.org/3/distutils/builtdist.html
You cannot use pythia8 as a typical example, because it is not a typical Python package. Everything that I am telling you, however, is standard in the Python community. You argue like you know the Python ecosphere very well, but I think I know it better than you.I havent used python willingly for anything for some years and even before that i was not very good in it, so i completely agree.Concerning the Pythia -- see the next mail.Andrii

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by HDembinski** [comment]
I am closing this after merging the io changes into another branch.

**Pull request closed without merging**
